jobs:
  ci:
    name: Verify
    runs-on: ubuntu-20.04

    steps:
      - name: Pull
        uses: actions/checkout@v2
      - name: Pull Deps
        run: sudo apt-get update && sudo apt-get install -y libhwloc15 unrar
      - name: Execute Tests
        run: ./workflow/check

name: Test

on:
  schedule:
    - cron: "35 */6 * * *"
